"""Launch an isolated copy with a test-only probe; never read launcher/account metadata."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import time
import zipfile
from build import argument_file

HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[1]
WORK=ROOT/'.cache/poc-cursor-20261009'
CLIENT=WORK/'client'

def info(path):
    return {'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'size':path.stat().st_size}

def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--jdk',type=Path,required=True)
    p.add_argument('--classpath-file',type=Path,required=True)
    p.add_argument('--offline-launch-args',type=Path,required=True,help='Arguments previously generated by a synthetic offline test, not launcher arguments')
    p.add_argument('--restart',action='store_true',help='Reuse this test copy after its previous process has stopped')
    a=p.parse_args()
    if CLIENT.exists() and not a.restart: raise RuntimeError('Test client already exists; use --restart only after stopping its process')
    if a.restart:
        import ctypes
        kernel=ctypes.WinDLL('kernel32',use_last_error=True)
        kernel.OpenProcess.restype=ctypes.c_void_p
        kernel.GetExitCodeProcess.argtypes=[ctypes.c_void_p,ctypes.POINTER(ctypes.c_ulong)]
        kernel.CloseHandle.argtypes=[ctypes.c_void_p]
        record=json.loads((WORK/'launch.json').read_text())
        handle=kernel.OpenProcess(0x1000,False,record['pid'])
        if handle:
            code=ctypes.c_ulong()
            kernel.GetExitCodeProcess(handle,ctypes.byref(code));kernel.CloseHandle(handle)
            if code.value==259:raise RuntimeError('Prior test process still running')
        stamp=str(int(time.time()))
        for name in ['launch.log','launch.json']:
            path=WORK/name
            if path.exists():path.rename(WORK/(path.stem+'-'+stamp+path.suffix))
        result=CLIENT/'cursor-test/result.json'
        if result.exists():result.rename(result.with_name('result-'+stamp+'.json'))
    WORK.mkdir(parents=True,exist_ok=True)
    lines=a.classpath_file.read_text(encoding='utf-8').splitlines()
    cp=lines[lines.index('-classpath')+1].strip('"')
    classes=WORK/'probe-classes';classes.mkdir(exist_ok=True)
    sources=sorted((HERE/'src/integration/java').rglob('*.java'))
    argument_file(WORK/'compile.args',['--release','21','-encoding','UTF-8','-proc:none','-classpath',cp,'-d',classes,*sources])
    subprocess.run([str(a.jdk/'bin/javac.exe'),'@'+str(WORK/'compile.args')],check=True)
    for directory in ([] if a.restart else ['mods','kubejs/assets','kubejs/data','kubejs/startup_scripts','kubejs/client_scripts','kubejs/server_scripts','config','defaultconfigs','resourcepacks','skyblockbuilder/exports']):
        source=ROOT/directory
        if not source.is_dir():continue
        for file in source.rglob('*'):
            if not file.is_file():continue
            name=file.relative_to(ROOT).as_posix()
            if re.search(r'credential|password|secret|token|account|session|auth|web_server|probe-settings|\.bak$|/search_index/|/inventoryprofilesnext/',name,re.I):continue
            target=CLIENT/name;target.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(file,target)
    shutil.copy2(HERE/'build/poc-cursor-1.0.0.jar',CLIENT/'mods/poc-cursor-1.0.0.jar')
    with zipfile.ZipFile(CLIENT/'mods/poc-cursor-probe.jar','w',zipfile.ZIP_DEFLATED) as z:
        for file in classes.rglob('*.class'):z.write(file,file.relative_to(classes).as_posix())
        z.writestr('META-INF/neoforge.mods.toml','modLoader="javafml"\nloaderVersion="[4,)"\nlicense="MIT"\n[[mods]]\nmodId="poc_cursor_probe"\nversion="1.0"\ndisplayName="Cursor Compatibility Probe (test only)"\n')
    (CLIENT/'options.txt').write_text('lang:zh_cn\nfullscreen:false\noverrideWidth:1280\noverrideHeight:800\nguiScale:2\nrenderDistance:3\nsimulationDistance:5\nmipmapLevels:0\nmaxFps:60\nresourcePacks:["vanilla","mod_resources"]\n',encoding='utf-8')
    # The final probe disables the cursor; reset only this mod's test-copy settings for reruns.
    (CLIENT/'config/poc-cursor-client.toml').write_text('customCursor = true\nclickEffects = true\ndurationMs = 420\n',encoding='utf-8')
    # The updater remains installed to test coexistence, with no network/version prompt.
    # Missing pack metadata makes its own documented failure branch stop checking this test profile.
    for filename in ['pack.json','baseline.json','latest.json']:
        target=CLIENT/'config/poc-updater'/filename
        if target.is_file():target.unlink()
    protected={}
    for directory in ['mods','kubejs/startup_scripts','kubejs/client_scripts','kubejs/server_scripts','kubejs/data','config/ftbquests/quests','config/fancymenu']:
        for file in (ROOT/directory).rglob('*'):
            if file.is_file():protected[file.relative_to(ROOT).as_posix()]=info(file)
    for filename in ['options.txt']:
        if (ROOT/filename).is_file():protected[filename]=info(ROOT/filename)
    if not a.restart:(WORK/'protected-before.json').write_text(json.dumps(protected,ensure_ascii=False,indent=2),encoding='utf-8')
    # This known-provenance file was made with accessToken=0 by an earlier isolated test.
    args=[v.strip('"') for v in a.offline_launch_args.read_text(encoding='gbk').splitlines()]
    substitutions={'--gameDir':str(CLIENT),'--username':'POC_Cursor_Test','--uuid':'3452285a82ee3f709e21d4a650853817','--accessToken':'0','--width':'1280','--height':'800'}
    for key,value in substitutions.items():
        if key in args:args[args.index(key)+1]=value
    args=[('-Xmx4G' if v.startswith('-Xmx') else v) for v in args]
    args.insert(0,'-Dfile.encoding=UTF-8')
    argument_file(WORK/'launch.args',args,native=True)
    with (WORK/'launch.log').open('wb') as log:
        process=subprocess.Popen([str(a.jdk/'bin/javaw.exe'),'@'+str(WORK/'launch.args')],cwd=CLIENT,stdout=log,stderr=subprocess.STDOUT,creationflags=subprocess.CREATE_NO_WINDOW)
    record={'pid':process.pid,'started':time.time(),'client':str(CLIENT),'production_mod':info(CLIENT/'mods/poc-cursor-1.0.0.jar'),'mod_jars':len(list((CLIENT/'mods').glob('*.jar')))}
    (WORK/'launch.json').write_text(json.dumps(record,indent=2),encoding='utf-8')
    print('Isolated client started, PID',process.pid,'JARs',record['mod_jars'])

if __name__=='__main__':main()
