VersionLiteLoader:False
Info:正式版 1.21.1, NeoForge 21.1.209
VersionVanilla:21.0.1
VersionOriginalMain:21
VersionApiCode:21010209
VersionVanillaName:1.21.1
VersionNeoForge:21.1.209
ReleaseTime:2024-08-08 20:24
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/NeoForge.png
VersionArgumentIndieV2:True
VersionOriginalSub:1
VersionOriginal:1.21.1
State:7
