ServerEvents.recipes(e=>{
    e.recipes.custommachinery.custom_machine('custommachinery:multi_block_machine',100)
    .requireEnergy(100000)
    .requireItem("25x minecraft:bedrock")
    .requireItem('3x minecraft:ancient_debris')
    .requireItem('17x minecraft:obsidian')
    .requireItem('minecraft:redstone_block')
    .requireItem('allthemodium:allthemodium_block')
    .requireItem('8x enderio:fluid_tank')
    .requireItem('minecraft:chest')
    .produceItem('rain:structure_void_mining_machine-3')

     e.recipes.custommachinery.custom_machine('custommachinery:multi_block_machine',100)
    .requireEnergy(100000)
    .requireItem("49x minecraft:bedrock")
    .requireItem('20x minecraft:iron_block')
    .requireItem('minecraft:redstone_block')
    .requireItem('4x mekanism:ultimate_fluid_tank')
    .requireItem('20x alltheores:steel_block')
    .requireItem('5x advanced_ae:quantum_alloy_block')
    .requireItem('10x alltheores:platinum_block')
    .requireItem('4x alltheores:nickel_block')
    .requireItem('6x oritech:machine_core_7')
    .requireItem('6x naturesaura:golden_leaves')
    .produceItem('rain:structure_dyeing')
})