#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Oct 04 16:00:25 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=15
shaderPack=photon_v1.2a.zip
